=== moomoohk/moobootstrap/assets/xml/moobootstrap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.moomoohk.github.io/moobootstrap" xmlns:mbt="http://www.moomoohk.github.io/moobootstrap"
	elementFormDefault="qualified">
	<xs:element name="BootstrapChangelog">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RemoteBuildNumber" type="xs:int"
					maxOccurs="1" minOccurs="1"/>
				<xs:element name="Builds" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Build" maxOccurs="unbounded"
								minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="VersionString" type="xs:string"
											maxOccurs="1" minOccurs="1" default="1.0" />
										<xs:element name="ChangeList" maxOccurs="1"
											minOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Change" maxOccurs="unbounded"
														minOccurs="1" default="Initial">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="type" type="mbt:ChangeType"
																		use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="BuildNumber" type="xs:int"
										use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="UniqueBuildNumber">
						<xs:selector xpath=".//*" />
						<xs:field xpath="@BuildNumber" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ChangeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="addition" />
			<xs:enumeration value="removal" />
			<xs:enumeration value="modification" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== moomoohk/moobootstrap/website/assets/xml/moobootstrap.xml
<?xml version="1.0" encoding="UTF-8"?>
<mbt:BootstrapChangelog xmlns:mbt="http://www.moomoohk.github.io/moobootstrap" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.moomoohk.github.io/moobootstrap moobootstrap.xsd ">
  <mbt:RemoteBuildNumber>0</mbt:RemoteBuildNumber>
  <mbt:Builds>
    <mbt:Build BuildNumber="0">
      <mbt:VersionString>1.0</mbt:VersionString>
      <mbt:ChangeList>
        <mbt:Change type="addition">Initial</mbt:Change>
      </mbt:ChangeList>
    </mbt:Build>
    <mbt:Build BuildNumber="1">
      <mbt:VersionString>1.0</mbt:VersionString>
      <mbt:ChangeList>
        <mbt:Change type="other">Initial</mbt:Change>
      </mbt:ChangeList>
    </mbt:Build>
    <mbt:Build BuildNumber="2">
      <mbt:VersionString>1.0</mbt:VersionString>
      <mbt:ChangeList>
        <mbt:Change type="other">Initial</mbt:Change>
      </mbt:ChangeList>
    </mbt:Build>
  </mbt:Builds>
</mbt:BootstrapChangelog>
